---
name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'
    - run: go version
    - run: go mod download

    - name: golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
        golangci-lint run
    - name: test
      run: |
        bash scripts/codecov-test.sh
        curl -s https://codecov.io/bash > /tmp/codecov.sh
        bash /tmp/codecov.sh

    - name: remove changes
      # Sometimes it is failed to release by goreleaser due to changes of go.sum
      run: git checkout -- .
    - name: fetch tags to release
      run: git fetch --tags
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run GoReleaser (skip publish)
      uses: goreleaser/goreleaser-action@v2
      if: "! startsWith(github.ref, 'refs/tags/')"
      with:
        version: latest
        args: release --rm-dist --snapshot
